name: dicoding_storyapp_awal
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  camera: ^0.10.5+5
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  geocoding: ^2.1.1
  get: ^4.6.5
  go_router: ^12.0.1
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  image: ^4.1.3
  image_picker: ^1.0.4
  json_annotation: ^4.8.1
  location: ^5.0.3
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  freezed: ^2.4.5

  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
